import './fonts';
import './globals.css';

import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { Header } from '@/widgets/Header/ui/Header';
import { NavigationMobile } from '@/widgets/NavigationMobile/ui/NavigationMobile';
import QueryClientProvider from './QueryClientProvider';

export const metadata: Metadata = {
  title: 'Greenshop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'antialiased'}>
        <NuqsAdapter>
          {/* <SessionProvider> */}
          <QueryClientProvider>
            <div className="pb-[5rem] md:pb-0 flex flex-col min-h-screen">
              <Header />
              {children}
            </div>
            <NavigationMobile />
          </QueryClientProvider>
          {/* </SessionProvider> */}
        </NuqsAdapter>
      </body>
    </html>
  );
}
